name = "nik-mods-payments"
main = "worker/tip-payment-worker.js"
compatibility_date = "2024-01-01"

# DO NOT put FAMGATEWAY_API_KEY here.
# FAMGATEWAY_API_KEY is securely configured as an encrypted Secret in Cloudflare.

